Fix error when running a single test
The require statement for the printer doesn't replace the general
one for the module. It's actually unclear how this worked without
it, but I don't think that's worth investigating.

Error, for reference:

  /govuk/government-frontend/test/test_helper.rb:10:in `<top (required)>': undefined method `config' for I18n::Coverage:Module (NoMethodError)