Set scss_lint-govuk to 'require: false' in Gemfile
When running tests I was getting this error:
`ActionView::Template::Error: undefined method `bubbles?' for true:Sass::Script::Tree::Literal`

The solution is suggested here https://github.com/sds/scss-lint/issues/278, specifically
"You should only require scss-lint explicitly in your code so that the monkey patching code
doesn't get loaded automatically. You can then explicitly load it for the cases where you need it"

Putting it first in the rake tasks seems to stop it erroring as well.