Specify all css classes in one attribute
The time element in this component specified two class attributes
for two classes, this is causing the E2E tests to return a failure
RuntimeError: In backend response: '126:117: ERROR: Attribute class redefined'